"""empty message

Revision ID: 913c19281ca2
Revises: 
Create Date: 2026-04-15 15:06:47.874430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913c19281ca2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('layout', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('card_faces', sa.String(length=100), nullable=True))

    with op.batch_alter_table('cube', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_id', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint(None, ['share_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cube', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('share_id')

    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('card_faces')
        batch_op.drop_column('layout')

    # ### end Alembic commands ###
