"""Add card_id foreign key to card_face table

Revision ID: f309cdbbd0d1
Revises: 913c19281ca2
Create Date: 2026-04-16 00:23:26.884254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f309cdbbd0d1'
down_revision = '913c19281ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('card_faces')

    with op.batch_alter_table('card_face', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'card', ['card_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_face', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('card_id')

    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_faces', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
